---
all:
  children:
    development:
      hosts:
        dev-server-1:
          ansible_host: 192.168.1.10
          ansible_user: dev-user
          ansible_port: 22
        dev-server-2:
          ansible_host: 192.168.1.11
          ansible_user: dev-user
          ansible_port: 22
      vars:
        env: development
        docker_registry: dev-registry.example.com

    staging:
      hosts:
        staging-server-1:
          ansible_host: 192.168.2.10
          ansible_user: stage-user
          ansible_port: 22
        staging-server-2:
          ansible_host: 192.168.2.11
          ansible_user: stage-user
          ansible_port: 22
      vars:
        env: staging
        docker_registry: stage-registry.example.com

    production:
      hosts:
        prod-server-1:
          ansible_host: 3.75.142.219
          ansible_user: ubuntu
          ansible_port: 22
      vars:
        env: production
        docker_registry: doramar97/my-app-nov

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /root/aws-keys/november.pem
    