[production]
18.195.169.60 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/aws-keys/november.pem
3.120.210.235 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/aws-keys/november.pem


[development]
3.72.53.64 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/aws-keys/november.pem
