pipeline {
  agent { label 'worker' }


  environment {
    DOCKER_CREDENTIALS = credentials('docker-cred')

  }
  
  stages {
    stage('Checkout Git repository') {
        steps {
            git branch: 'main', url: 'https://github.com/dor-amar/ansible.git'
        }
    }

    
    stage('Build Docker image') {
        steps {
            script {
                dir('november-full-cicd') {
                    sh "docker build -t doramar97/full-cicd-example:${env.BUILD_NUMBER} ."
                }

            }
        }
    }


    stage('Login to Docker') {
        steps {
            script {
                sh "echo ${DOCKER_CREDENTIALS_PSW} | docker login -u ${DOCKER_CREDENTIALS_USR} --password-stdin"
            }
        }
    }

    stage('Push Docker Image') {
        steps {
            script {
                sh "docker push doramar97/full-cicd-example:${env.BUILD_NUMBER}"
            }
        }
    }



    // stage('Deployment') {
    //     steps {
    //         script {
    //             sh """
    //             docker run -d -p 80:80 doramar97/my-app-nov:latest
    //             """
    //         }
    //     }
    // }
  }
}



