pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'doramar97'
        DOCKER_IMAGE = 'my-app-nov'
        DOCKER_CREDENTIALS = 'docker-registry-credentials'
    }

    triggers {
        githubPush()
    }

    parameters {
        choice(name: 'DEPLOY_ENV', choices: ['development', 'staging', 'production'], description: 'Deployment Environment')
    }

    stages {
        stage('Prepare') {
            steps {
                script {
                    // Set VERSION variable inside a script block
                    VERSION = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('cicd-jenkins-ansible') {
                    script {
                        docker.build("${DOCKER_IMAGE}:${VERSION}", "-f Dockerfile .")
                    }
                }
            }
        }

        stage('Push to Registry') {
            steps {
                script {
                    docker.withRegistry("https://${DOCKER_REGISTRY}", DOCKER_CREDENTIALS) {
                        docker.image("${DOCKER_IMAGE}:${VERSION}").push()
                        docker.image("${DOCKER_IMAGE}:${VERSION}").push('latest')
                    }
                }
            }
        }

        stage('Deploy with Ansible') {
            steps {
                dir('cicd-jenkins-ansible') {
                    script {
                        ansiblePlaybook(
                            playbook: 'ansible/deployment.yaml',
                            inventory: 'ansible/inventory/hosts.yml',
                            extras: "-e env=${params.DEPLOY_ENV} -e version=${VERSION}",
                            colorized: true
                        )
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Deployment successful to ${params.DEPLOY_ENV} environment!"
        }
        failure {
            echo "Deployment failed! Check logs for details."
        }
        always {
            script {
                sh "docker rmi ${DOCKER_IMAGE}:${VERSION} || true"
            }
        }
    }
}
