---
- name: Deploy Python Web Application Using Docker
  hosts: ubuntu
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Clone the application code from GitHub
      git:
        repo: "https://github.com/dor-amar/ansible.git"  # Replace with your repo URL
        dest: "/var/www/myapp"

    - name: Build the Docker image for the Python app
      command: sudo docker build -t simple-flask-api:latest . 
      args:
        chdir: "/var/www/myapp/automated-deployment/app"  # Where the Dockerfile is located

    - name: Stop and remove the existing container if it exists
      docker_container:
        name: simple-flask-api
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Run the new Python app container
      docker_container:
        name: simple-flask-api
        image: simple-flask-api:latest
        state: started
        ports:
          - "5000:5000"  # Map port 5000 on the server to port 5000 inside the container
        restart_policy: always
