---
- name: Deploy Flask application
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv
        - git

    - name: Clone the Flask application repository
      git:
        repo: 'https://github.com/dor-amar/jenkins.git'
        dest: /opt/flaskapp

    - name: Install Flask in virtual environment
      command: /opt/flaskapp/venv/bin/pip install flask

    - name: Create systemd service for Flask app
      copy:
        dest: /etc/systemd/system/flaskapp.service
        content: |
          [Unit]
          Description=Flask Application

          [Service]
          ExecStart=/opt/flaskapp/venv/bin/python /opt/flaskapp/project/app.py
          Restart=always
          User=www-data
          Group=www-data
          Environment=PYTHONUNBUFFERED=1

          [Install]
          WantedBy=multi-user.target

    - name: Start Flask app service
      systemd:
        name: flaskapp
        state: started
        enabled: yes