---
- name: Deploy a Simple HTML Page with Nginx
  hosts: webservers
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Deploy HTML page from template
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
