---
- name: Update web servers
  hosts: all

  tasks:
  - name: Create files with a loop 
    file:
      path: /tmp/ansible- {{ item }}
      state: touch
    loop:
     - 1
     - 2
     - 3
     - 4

