- hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Nginx
      service:
        name: nginx
        state: present
      when: ansible_os_family == 'RedHat'
