---
- hosts: webservers
  become: yes
  tasks:
    - name: Enable SELinux
      selinux:
        state: enabled
      when: ansible_os_family == 'RedHat'
      register: enable_selinux

    - debug:
        msg: "SELinux enabled. Please restart the server to apply changes."
      when: enable_selinux.changed
