- name: Deploy a Static Website
  hosts: webservers
  become: yes
  vars:
    web_content: ./index.html
    web_dest: /var/www/html/

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Copy website files
      copy:
        src: "{{ web_content }}"
        dest: "{{ web_dest }}"
        owner: apache
        group: apache
        mode: 0644

    - name: Ensure index.html exists
      file:
        path: /var/www/html/index.html
        state: touch
        owner: apache
        group: apache
        mode: 0644
