- name: Install Apache Web Server
  hosts: allservers
  become: yes
  tasks:
    - name: Install Apache on RedHat systems
      apt:
        name: httpd
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache on Amazon systems
      yum:
        name: apache2
        state: present
      when: ansible_os_family == "Amazon"
