- name: Install Apache Web Server
  hosts: all
  become: yes
  tasks:
    - name: Install Apache on RedHat systems
      dnf:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Apache on Amazon systems
      yum:
        name: apache2
        state: present
      when: ansible_os_family == "Amazon"
