---
- name: Manage Docker Containers
  hosts: amazonlinux
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Run nginx container
      docker_container:
        name: nginx
        image: nginx
        state: stopped
        ports:
          - "80:80"
